### ISSUE TITLE
Tags are displayed in source code only for Japanese sites

### ISSUE THREAD

**Issue by TomiakiNiwa** [MicrosoftDocs/sql-docs.ja-jp#229]
**Describe the bug**
In the Japanese page, the tag is displayed in the last sample source.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/ja-jp/sql/relational-databases/backup-restore/enable-sql-server-managed-backup-to-microsoft-azure?view=sql-server-2017'
2. Look at the last source.

**Expected behavior**
In English pages, it has not occurred.
There is a possibility that CSS error occurred during translation.

**Screenshots**
![image](https://user-images.githubusercontent.com/48230525/53776583-cc9c6c80-3f39-11e9-9767-daa65f991fa5.png)

**Desktop (please complete the following information):**
all

**Smartphone (please complete the following information):**
all

**Additional context**
none

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #1717](https://github.com/MicrosoftDocs/sql-docs/issues/1717) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @TomiakiNiwa 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/1717

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
