### ISSUE TITLE
TOC for SQL ja-jp document is not translated.

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/sql-docs.ja-jp#364]
TOC for SQL ja-jp document is not translated.
![SQL_j](https://user-images.githubusercontent.com/40815708/60560893-a0c8b080-9d8c-11e9-956a-ea86f53c6daf.png)

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
**Can you please provide the URL where you found this issue?**

Kind regards,
Microsoft DOCS International Team

**Comment by hyoshioka0128** [comment]
Hello, @CeciAc 

Fixed, please close it.
Close #364

![sqlserver_j](https://user-images.githubusercontent.com/40815708/61549882-24bcb100-aa8c-11e9-9771-16ae2be0ff39.png)
"https://docs.microsoft.com/ja-jp/sql/sql-server/what-s-new-in-sql-server-2017?view=sql-server-2017"
