### ISSUE TITLE
broken rendering

### ISSUE THREAD

**Issue by yujiorama** [MicrosoftDocs/sql-docs.ja-jp#946]
From `In [!INCLUDEssCurrent], `, markdown rendering was broken.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4f33f7c8-745d-bdd0-fe14-2c1dac6875de
* Version Independent ID: 6db1bff2-e212-3337-7599-ea2b94019e04
* Content: [システムストアドプロシージャ (Transact-sql) - SQL Server](https://docs.microsoft.com/ja-jp/sql/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ja-jp/blob/live/docs/relational-databases/system-stored-procedures/system-stored-procedures-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by srvbpigh** [comment]
Hello, @yujiorama
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #4360](https://github.com/MicrosoftDocs/sql-docs/issues/4360) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @yujiorama, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/4360. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
